<!--<script type="text/javascript">
window.onload = function()
{
CKEDITOR.replace('parrafo');
}
</script>-->
<td valign="top">
    <?php echo $this->msg?>
    <div id="centerPane">
        <div id="toolbar">
            <a class="modules" href="<?php //$this->baseUrl() ?>/admin/arty/index">Collections</a> &gt; <a class="actualités" href="<?php //$this->baseUrl() ?>/admin/index/actualites/"><?php echo $this->params['action'] ?></a> &gt; New
            <div id="main">
                <!--   <h2 class="top"></h2>-->
                <div id="form">
                    <?php echo $this->form?>    
                </div>
            </div>

            <!-- <div id="options" class="column" >
                                 </div>-->

        </div>
</td>