<td valign="top">
    <div id="centerPane">
        <div id="toolbar">
           <a class="modules" href="<?php $this->baseUrl()?>/admin/pointventa/index">Liste Point Vente</a> &gt; <a class="actualités" href="<?php $this->baseUrl()?>/admin/index/actualites/"><?php echo $this->params['action']?></a> &gt; Modifier               
        <div id="main">
            <!--   <h2 class="top"></h2>-->
            <div id="form">
                <form id="frmDevenir" enctype="multipart/form-data" method="post" action="">
                    <?php 
                        echo $this->render('render/listaIdioma.phtml',
                            array(
                                'idms' => $this->idms,
                                'lang' => $this->lang,
                            )
                        );
                    ?>


                    <div class="table_admin">
                        <div class="table_admin_head"></div>
                        <div align="center" class="table_admin_body">
                            <input type="hidden" value="3" name="id">
                            <table cellspacing="0" cellpadding="0" border="0" width="100%" class="table_form">
                               
                                <tfoot>
                                    <tr>
                                        <td align="right" valign="bottom" colspan="3">
                                            <input type="submit" value="Valider" name="">
                                            <input type="button" onclick="location.href='/admin/ciudades';" value="Back" name="cancel">    </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <div class="table_admin_foot"></div>
                    </div>
                </form>
                <script>
                    contenido_textarea = ""
                    num_caracteres_permitidos = 5000
                    function valida_longitud(){
                        num_caracteres = document.forms[0].description.value.length
	
                        if (num_caracteres == num_caracteres_permitidos){
                            contenido_textarea = document.forms[0].description.value	
                        }else{
                            document.forms[0].description.value = contenido_textarea
                        }
                    }

                </script>
            </div>
        </div>

        <!-- <div id="options" class="column" >
                             </div>-->

    </div>
</td>

<script>

function getComboIdioma(value){
    var urls = document.URL;
    var data = urls.split('/idlang/');
    location.href = data[0] + '/idlang/' +  value
}
</script>