<td valign="top">
    <div id="centerPane">
        <div id="toolbar">
           <a class="modules" href="<?php $this->baseUrl()?>/admin/pointventa/index">Ciudades</a> -&gt; <a class="actualités" href="<?php $this->baseUrl()?>/admin/index/actualites/"><?php echo $this->params['action']?></a> -&gt; Nouveau               
        <div id="main">
            <!--   <h2 class="top"></h2>-->
            <div id="form">
                    <?php 
                        echo $this->render('render/listaIdioma.phtml',
                            array(
                                'idms' => $this->idms,
                                'lang' => $this->lang,
                            )
                        );
                    ?>
                    <div class="table_admin">
                        <div class="table_admin_head"></div>
                        <div align="center" class="table_admin_body">
                            <input type="hidden" value="3" name="id">
                            <form id="frmDevenir" enctype="multipart/form-data" method="post" action="">
                                <table cellspacing="0" cellpadding="0" border="0" width="100%" class="table_form">
                                    <tbody>
                                        <tr><th colspan="2">
                                            </th></tr>

                                        <tr>
                                            <td align="left" width="20%">Pais : </td>
                                            <td align="left" width="80%"> 
                                                <input type="hidden" name="idPais" value="<?php echo $this->data['idPais']?>" />
                                                <input type="text" value="<?php echo $this->data['nombrePaisIdioma']?>"  size="20" name="hnombrePais" disabled="disabled" />
                                            </td>
                                        </tr>
                                       
                                        <tr>
                                            <td align="left" width="20%">City : *</td>
                                            <td align="left" width="80%">
                                                <input type="text" class="required" size="40" maxlength="100" name="nombreCiudad" />
                                            </td>
                                        </tr>

                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td align="right" valign="bottom" colspan="3">
                                                <input type="submit" value="Valider" name="">
                                                <input type="button" onclick="location.href='/admin/lista-ciudades/id/' . <?php echo $this->data['idPais']?>;" value="Back" name="cancel">    </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </form>
                        </div>
                        <div class="table_admin_foot"></div>
                    </div>
                
                <script>
                    contenido_textarea = ""
                    num_caracteres_permitidos = 5000
                    function valida_longitud(){
                        num_caracteres = document.forms[0].description.value.length
	
                        if (num_caracteres == num_caracteres_permitidos){
                            contenido_textarea = document.forms[0].description.value	
                        }else{
                            document.forms[0].description.value = contenido_textarea
                        }
                    }

                </script>
            </div>
        </div>

        <!-- <div id="options" class="column" >
                             </div>-->

    </div>
</td>