<td valign="top">
    <div id="centerPane">
        <div id="toolbar">
            <a class="modules" href="<?php $this->baseUrl() ?>/admin/index">Ini</a> &gt; <a class="actualités" href="<?php $this->baseUrl() ?>/admin/index/actualites/"><?php echo $this->params['action'] ?></a> &gt; Modifier               
        </div>
        <div id="main">
            <!--   <h2 class="top"></h2>-->
            <div id="form">
                <?php
                echo $this->render(
                        'render/listaIdioma.phtml', array(
                    'idms' => $this->idms,
                    'lang' => $this->lang,
                ));
                ?>

                <!-- End Language -->
                <div class="table_admin">
                    <div class="table_admin_head"></div>
                    <div align="center" class="table_admin_body">
                        <input type="hidden" value="9" name="id">
                        <table width="100%" cellspacing="0" cellpadding="0" border="0"><?php //class="table_form"; ?>
                            <tbody>
                                <?php
                                foreach ($this->data as $value):

                                    if ((int) $value['estadoMenuBase'] == 1):
                                        $css = "shadow";
                                        $alert = CAlertMenuOFF;
                                        $title = CTitleMenuOFF;
                                    else:
                                        $css = 'column-admin';
                                        $alert = CAlertMenuOFF;
                                        $title = CTitleMenuOFF;
                                    endif;
                                    ?>
                                    <tr class="<?php echo $css; ?>">
                                        <td width="40%"><img border="0" class="icon" alt="" src="/images/icons/layout_sidebar.png"><?php echo $value['nombreMenu']; ?></td>
                                        <td width="45%"><?php echo $value['nombreMenu']; ?></td>
                                        <td align="right" width="15%">
                                            <a href="/admin/index/menueditar/id/<?php echo $value['idMenu'] ?>" title="Modifier">
                                                <img border="0" src="/images/icons/edit.gif">
                                            </a>
                                            <!--                                                <a class="status-config" href="/admin/module/config/id/actualites/mode/desinstaller" title="Enlever le module">-->
                                            <img border="0" title="<?php echo $title; ?>" src="/images/icons/process_remove.png" onclick="deleteMenu('<?php echo $value['idMenuBase'] ?>','<?php echo $alert; ?>')" style="cursor: pointer;" >
                                            <!--                                                </a>-->

                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                            <div id="menu-action" class="menu-action"></div>
                            </tfoot>
                        </table>
                    </div>
                    <div class="table_admin_foot"></div>
                </div>


                <!-- jQuery -->
            </div>
        </div>

        <!-- <div id="options" class="column" >
                             </div>-->

    </div>
</td>
<script type="text/javascript">
  
    function deleteMenu(id,mensaje){

        confirmacion=confirm(mensaje);
        if(confirmacion){
            $.ajax({
                data:'id=' + id,
                async:1,
                type:"POST",dataType:"html",
                contentType: "application/x-www-form-urlencoded",
                url:"/admin/index/ajax/case/deleteMenu",
                beforeSend:beforedel,
                success:successdel,
                timeout:80000,
                error:errordel 
            });
        }
    }
    
    function beforedel(){
        $("#menu-action").html("<img src='/images/cargando.gif'>");
    }

    function successdel(datos){
        $("#menu-action").html('');
        location.href = document.URL
    }

    function errordel(){
        $("#menu-action").text("Problemas en el servidor.");
    } 
    
</script>