<td valign="top">
    <div id="centerPane">
        <div id="toolbar">
            <a class="modules" href="<?php $this->baseUrl() ?>/admin/index">Ini</a> &gt; <a class="actualités" href="<?php $this->baseUrl() ?>/admin/index/actualites/"><?php echo $this->params['action'] ?></a> &gt; Modifier               
        </div>
        <div id="main">
            <!--   <h2 class="top"></h2>-->
            <div id="form">
                <?php
                echo $this->render(
                        'render/listaIdioma.phtml', array(
                    'idms' => $this->idms,
                    'lang' => $this->lang,
                ));
                ?>
           <!-- End Language -->
                <div class="table_admin">
                    <div class="table_admin_head"></div>
                    <div align="center" class="table_admin_body">
                        <input type="hidden" value="9" name="id">
                        <div><?php echo is_array($this->mensaje)?$this->mensaje[0]:''; ?></div>
                        <fieldset>
                            <legend 
                                style="cursor : pointer" 
                                onclick="openCloseLayer('listmodules')">
                                <img align="top" src="/images/icons/package.png"> Liste de actualites</legend>
                            <div id="listmodules" style="display: block; padding: 2px 10px;">
                                <table width="100%" cellspacing="0" cellpadding="0" border="0">
                                    <thead>
                                        <tr>
                                            <th>Title</th>
                                            <th>Sub Title</th>
                                            <th>Imagen</th>
                                            <th>Link</th>
                                            <th>Options</th>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        <?php
                                        foreach ($this->listaactualites as $value):
                                            if ((int) $value['estadoactualites'] == 1):
                                                $css = "shadow";
                                                $alert = CAlertMenuOFF;
                                                $title = CTitleMenuOFF;
                                            else:
                                                $css = 'column-admin';
                                                $alert = CAlertMenuOFF;
                                                $title = CTitleMenuOFF;
                                            endif;
                                            ?>
                                            <tr class="<?php echo $css; ?>">
                                                <td width="35%" >
<!--                                                    <img border="0" class="icon" alt="" src="/images/icons/layout_sidebar.png">-->
                                                    <?php echo $value['tituloactualitesIdioma']; ?>
                                                </td>
                                                <td width="25%">
                                                    <?php echo $value['subTituloactualitesIdioma']; ?>
                                                </td>
                                                <td width="25%">
                                                    <img width="70" src="<?php echo $this->baseUrl() ?>/imagen-actualites/thums_<?php echo $value['imgactualites']; ?>" >
                                                </td>
                                                <td width="10%">
                                                    <a href="<?php echo $this->baseUrl() ?>/imagen-actualites/<?php echo $value['linkactualites']; ?>" target="_Black"><?php echo $value['linkMostraractualitesIdioma']?></a>
                                                </td>
                                                <td align="right" width="15%">
                                                    <a href="/admin/actualites/edit-actualites/id/<?php echo $value['idactualites'] ?>" 
                                                       title="Modifier">
                                                        <img border="0" src="/images/icons/edit.gif">
                                                    </a>
                                                    <!--                                                <a class="status-config" href="/admin/module/config/id/actualites/mode/desinstaller" title="Enlever le module">-->
                                                    <img border="0" 
                                                         title="<?php echo $title; ?>" 
                                                         src="/images/icons/process_remove.png" 
                                                         onclick="deleteMenu('<?php echo $value['idMenuBase'] ?>','<?php echo $alert; ?>')" 
                                                         style="cursor: pointer;" >
                                                    <!--                                                </a>-->

                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td align="right" valign="bottom" colspan="5">
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <a href="/admin/actualites/new-actualite"> Nouveau</a>
                        </fieldset>

                    </div>
                    <div class="table_admin_foot"></div>
                </div>


                <!-- jQuery -->
            </div>
        </div>

        <!-- <div id="options" class="column" >
                             </div>-->

    </div>
</td>