<div id="editar-menu">
    
</div>
<td valign="top">
    <div id="centerPane">
        <div id="toolbar">
            <a class="modules" href="<?php $this->baseUrl() ?>/admin/index">Ini</a> &gt; <a class="actualités" href="<?php $this->baseUrl() ?>/admin/index/actualites/"><?php echo $this->params['action'] ?></a> &gt; Modifier               
        </div>
        <div id="main">
            <!--   <h2 class="top"></h2>-->
            <div id="form">
                <form id="frmActualites" method="post" action="" onsubmit="return saveMenuEdita(this);">
                    <div class="table_admin">
                        <div class="table_admin_head"></div>
                        <div align="center" style="background-color:#F7F7F7" class="table_admin_body">
                            <table width="100%" cellspacing="0" cellpadding="0" border="0">
                                <tbody><tr>
                                        <td>
                                            Version actuel: 
                                            <strong><?php echo $this->idiomaDefault['NombreIdioma'] ?></strong>
                                            &nbsp;&nbsp;&nbsp;
                                            Langue disponible:

                                        </td>
                                    </tr>
                                </tbody></table>


                        </div>        
                        <div class="table_admin_foot"></div>
                    </div>
                    <!-- End Language -->
                    <div class="table_admin">
                        <div class="table_admin_head"></div>
                        <div align="center" class="table_admin_body">
                            <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table_form">
                                <tbody>
                                    <input type="hidden" value="<?php echo $this->idiomaDefault['idIdioma']?>" name="idIdioma">
                                    <input type="hidden" name="idMenu" id="idMenu">
                                    <input type="hidden" name="idMenuBase" id="idMenuBase">
                                    <tr>
                                        <td>Código :</td>
                                        <td><input type="text" name="hidMenu" id="hidMenu" disabled="disabled"></td>
                                    </tr>
                                    <tr>
                                        <td>Nombre :</td>
                                        <td><input type="text" name="nombreMenu" id="nombreMenu"></td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td valign="bottom" align="right" colspan="3">
                                            <input type="submit" value="Guardar" name="validate">

                                    </tr>
                                </tfoot>
                               
                            </table>
                        </div>
                        <div class="table_admin_foot"></div>
                    </div>
                </form>

                <!-- jQuery -->
            </div>
        </div>

        <!-- <div id="options" class="column" >
                             </div>-->

    </div>
</td>
<script type="text/javascript">
    
   
        $.getJSON('/admin/json/json/case/getEditMenu', {cod:'<?php echo $this->cod?>'}, 
            function(json){
                $.each(json, function(i,item){
                    $("#idMenu").attr('value',json[i].idMenu); 
                    $("#idMenuBase").attr('value',json[i].idMenuBase); 
                    $("#hidMenu").attr('value',json[i].idMenu); 
                    $("#nombreMenu").attr('value',json[i].nombreMenu);
                });
            });
    
	//$('#id').attr('value',id);
	//comboNotaAnual(id);

    function saveMenuEdita(id){	
        var data = $(id).serialize();
        
        $.ajax({
            data: data,
            async:1,
            type:"POST",dataType:"html",
            contentType: "application/x-www-form-urlencoded",
            url:"/admin/index/ajax/case/saveMenuEdita",
            beforeSend:beforeload,
            success:successload,
            timeout:80000,
            error:errorload 
        });
        return false;
       
    }
    
    function beforeload(){
        $("#editar-menu").html("<img src='/images/cargando.gif'>");
    }

    function successload(datos){
       
        return false;
    }

    function errorload(){
        $("#editar-menu").text("Problemas en el servidor.");
    } 
    
    
</script>