<div id="page">
	<div  class="header-top"><?php echo $this->getTranslation('Idioma'); ?> <?php echo $this->ListLanguageLinksIcoAdmin(); ?>
	 <?php echo $this->CurrentAdminUser();?> 
	</div>
    <div id="header">
        <?php
        echo $this->RenderAdminMenu();
       ?>
	   <div id=bar_top>
	      <!--<img src="<?php echo $this->getBaseUrl();?>/images/px.gif" alt="" width='2000' height='2' border="0" />-->
	   </div>
    </div>
    <div id="pageShadow">
        <div id="pageInner" class="clearFix">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
   		 <tr>
        <td valign=top   class="sidebar" height=500 >
        	 <div id="sidebar" class="column">
                    <?php echo $this->RenderSidebar();?>
            </div>
        </td>
        <td valign=top>
        	           <div id="centerPane">
                <div id="toolbar">
                   <?php
                       echo $this->RenderLinks($this->toolbarLinks, 'rightLinks');
                      echo $this->RenderLinks($this->breadcrumbs, 'breadcrumbs',' ', null, ' > ');
                   ?>
                </div>
                <div id="main">
                  <!--   <h2 class="top"><?php echo $this->placeholder('formHeadline');?></h2>-->
                    <div id="form" >
                        <?php echo $this->RenderAlert();?>
                        <?php echo $this->layout()->form ?>
                    </div>
                </div>
				
               <!-- <div id="options" class="column" >
                    <?php //echo $this->RenderOptions();?>
                </div>-->
				
            </div>
        </td>
   		 </tr>
	</table>

           
			
 
        </div>
    </div>
    <div id="footer"></div>
</div>