<div id="content" class="layout_fluid_inner">
    <div class="inside">
<?php 
            $arrayOption = array(
            'menuIzquierda'=>$this->menuIzquierda,
            'itemSelect'=>$this->itemSelect,
            'actionName'=>$this->actionName,
            'lang'=>$this->lang,
            'controllerName'=>$this->controllerName
            );
        echo $this->render('render/menuizq.phtml',$arrayOption); //vista rederizada para el menu izquierda ?>
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <article class="box_article">
                    <h2>2011 - ADOPTEZ UN ARBRE</h2>								
                    <img class="imgRight" src="img/temp/img_mecenatversailles_1.jpg"/>
                    <p>En 2011, ce mécénat a pris la forme de l’adoption d’un arbre de l’Etoile Royale. 
                        Architecture végétale et paysagère, l’Etoile Royale est située au coeur de l’axe
                        majeur du parc de Versailles et date de la fin du XVIIe siècle. Pièce maîtresse de
                        la composition de Le Nôtre, elle était très dégradée, jusqu’à ce que l’’établissement
                        public du château, du musée et du domaine national de Versailles décide de la requalifier
                        par un réaménagement des allées et circulations et une vaste campagne de replantation
                        des structures d’alignement d’arbres.</p>
                    <a href="#"	 class="more">Adoptez un arbre</a>				
                </article>
                <article class="box_article">
                    <h2>2011 - ADOPTEZ UN ARBRE</h2>								
                    <img class="imgRight" src="img/temp/img_mecenatversailles_2.jpg"/>
                    <p>En 2011, ce mécénat a pris la forme de l’adoption d’un arbre de l’Etoile Royale. 
                        Architecture végétale et paysagère, l’Etoile Royale est située au coeur de l’axe
                        majeur du parc de Versailles et date de la fin du XVIIe siècle. Pièce maîtresse de
                        la composition de Le Nôtre, elle était très dégradée, jusqu’à ce que l’’établissement
                        public du château, du musée et du domaine national de Versailles décide de la requalifier
                        par un réaménagement des allées et circulations et une vaste campagne de replantation
                        des structures d’alignement d’arbres.</p>
                    <a href="#"	 class="more">Adoptez un arbre</a>				
                </article>							
            </div>
        </section>
    </div>
</div>