<div id="login_wrapper">
<?php if(is_array($this->element->getView()->messages) && count($this->element->getView()->messages)>0 ) { ?>
	        <?php foreach($this->element->getView()->messages as $index):    ?>               			
    <div class="error">
        <div class="error_inner">
            <strong>Access Denied</strong> | <span><?php echo  $index;?></span>
        </div>
    </div>
<?php  endforeach; } ?>
    <!--[if !IE]>start login<![endif]-->
    <form action="" method="<?php echo $this->element->getMethod(); ?>">
        <fieldset>			
            <h1 id="logo"><a href="#">websitename Administration Panel</a></h1>
            <div class="formular">
                <div class="formular_inner">					
                    <label>
                        <strong>Username:</strong>
                        <span class="input_wrapper">
                            <?php echo $this->element->login; ?>
<!--                            <input name="" type="text" />-->
                        </span>
                    </label>
                    <label>
                        <strong>Password:</strong>
                        <span class="input_wrapper">
                            <?php echo $this->element->password?>
<!--                            <input name="" type="password" />-->
                        </span>
                    </label>

                    <ul class="form_menu">
                        <li><span class="button"><span><span>Submit</span></span><input type="submit" name=""/></span></li>
                    </ul>

                </div>
            </div>
        </fieldset>
    </form>
    <!--[if !IE]>end login<![endif]-->
</div>
<?php 
//echo $this->form;
?>