   <img src="/images/px.gif" alt="" width='200' height='10' border="0" />
 	<form action="" method="post"  class="form">
        <div>Entrer votre login et votre mot de passe</div>

<table width="230" border="0" cellspacing="2" cellpadding="2">
    <tr>
        <td>Identifiant        </td>
        <td align="right">
            <?php echo $this->element->login; ?>
        </td>
    </tr>
    <tr>
        <td>Mot de passe        </td>

        <td align="right">
             <?php echo $this->element->password?>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <div style="float:left; width:70%;">
<!--                <a class="mdp" href="/admin/auth/resetpassword">Vous avez oublié votre mot de passe?</a>-->
            </div>
            <div style="float:right; width:30%;" align="right">

                 <input type="submit" name="access" value="Valider" />
            </div>
        </td>
    </tr>
</table>
        </form>