<div id="content" class="layout_fluid_inner">
    <div class="inside">
<?php
$arrayOption = array(
    'itemSelect'=>$this->itemSelect,
    'actionName'=>$this->actionName,
    'lang'=>$this->lang,
    'controllerName'=>$this->controllerName,
    'listaPais'=>$this->listaPais,
    );
echo $this->render('render/menuizq-pais.phtml',$arrayOption) ?>        
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <?php
                foreach($this->listaPuntoVenta as $index => $data): ?>
                <h2><?php echo $index; ?></h2>
                <div class="cf">
                    <?php foreach($data as $dataIndex): 
                        ?>
                    <div class="box_border box_pointvente">											
                        <div class="inner_thumb">
                             <p>
                                <?php echo $dataIndex['nombrePuntoVenta']; ?><br/>
                                <?php echo $dataIndex['direccionPuntoVenta']; ?><br/>
                                Tél : <?php echo $dataIndex['telefonoPuntoVenta']; ?><br/>
                            </p>
                            <a class="more" href="<?php echo $dataIndex['direccionWebPuntoVenta']; ?>"><?php echo $dataIndex['direccionWebPuntoVenta']; ?></a>
                            <?php 
                            if($dataIndex['fotos']!=''){
                            $arrayFotos = explode(',',$dataIndex['fotos']);
                            $arrayFotos = array_unique($arrayFotos);
                            } else {
                            $arrayFotos = array();    
                            }
                            if (count($arrayFotos)>0) {
                            ?>
                            <ul class="lst_thumb">
                                <?php foreach($arrayFotos as $indexfotos):?>
                                <li>
                                    <a href="/imgPuntoVenta/<?php echo $indexfotos?>" class="zoom" rel="thumb1">
                                        <img class="" width="25" height="25" src="/imgPuntoVenta/<?php echo $indexfotos?>"/>
                                    </a>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                            <?php } ?>
                        </div>
                    </div>	
                    <?php endforeach; ?>
                </div>	
                <?php endforeach;?>
<!--        <h2>PARIS</h2>
                <div class="cf">
                    <div class="box_border box_pointvente">											
                        <div class="inner_thumb">
                            <p>Boutique Jovoy<br/>
                                Parfums Rares<br/>
                                29, rue Danielle Casanova<br/>
                                75001 Paris<br/>
                                Tél : +33 (0)1 40 20 06 19</p>
                            <a class="more" href="#">www.jovoy.com</a>
                            <ul class="lst_thumb">
                                <li>
                                    <a href="img/temp/img_pointvente_1.jpg" class="zoom" rel="thumb1">
                                        <img class="" src="img/temp/thumb_pointvente_1.jpg"/>
                                    </a>
                                </li>
                                <li>
                                    <a href="img/temp/img_pointvente_2.jpg" class="zoom" rel="thumb1">
                                        <img class="" src="img/temp/thumb_pointvente_2.jpg"/>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>								
                    <div class="box_border box_pointvente">
                        <div class="inner_thumb">
                            <p>Boutique Jovoy<br/>
                                Parfums Rares<br/>
                                29, rue Danielle Casanova<br/>
                                75001 Paris<br/>
                                Tél : +33 (0)1 40 20 06 19</p>
                            <a class="more" href="#">www.jovoy.com</a>
                            <ul class="lst_thumb">
                                <li>
                                    <a href="img/temp/img_pointvente_1.jpg" class="zoom" rel="thumb1">
                                        <img class="" src="img/temp/thumb_pointvente_1.jpg"/>
                                    </a>
                                </li>
                                <li>
                                    <a href="img/temp/img_pointvente_2.jpg" class="zoom" rel="thumb1">
                                        <img class="" src="img/temp/thumb_pointvente_2.jpg"/>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="box_border box_pointvente">											
                        <div class="inner_thumb">
                            <p>Boutique Jovoy<br/>
                                Parfums Rares<br/>
                                29, rue Danielle Casanova<br/>
                                75001 Paris<br/>
                                Tél : +33 (0)1 40 20 06 19</p>
                        </div>
                    </div>									
                </div>	

                <h2>PARIS</h2>
                <div class="cf">

                    <div class="box_border box_pointvente">
                        <div class="inner_thumb">
                            <p>Boutique Jovoy<br/>
                                Parfums Rares<br/>
                                29, rue Danielle Casanova<br/>
                                75001 Paris<br/>
                                Tél : +33 (0)1 40 20 06 19</p>
                        </div>
                    </div>

                    <div class="box_border box_pointvente">											
                        <div class="inner_thumb">
                            <p>Boutique Jovoy<br/>
                                Parfums Rares<br/>
                                29, rue Danielle Casanova<br/>
                                75001 Paris<br/>
                                Tél : +33 (0)1 40 20 06 19</p>
                        </div>
                    </div>									
                </div>
                -->
            </div>	
        </section>
    </div>
</div>