<div id="content" class="layout_fluid_inner">
    <div class="inside">
        <?php echo $this->render('render/menuizq-pais.phtml') ?>        
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <h2>SITE INTERNET</h2>
                <div class="cf">
                    <?php foreach($this->listaPuntoVenta as $index): ?>
                    <div class="box_border box_pointvente">
                        <img class="imgLeft" src="<?php echo $index['imgPortalPuntoVenta']?>"/>
                        <div class="inner">
                            <a class="more" href="<?php echo $index['direccionWebPuntoVenta']?>"><?php echo $index['direccionWebPuntoVenta']?></a>
                        </div>
                    </div>								
                    <?php endforeach; ?>
                </div>	
            </div>	
        </section>
    </div>
</div>