<div id="content" class="layout_fluid_inner">
    <div class="inside">
<?php 
            $arrayOption = array(
            'menuIzquierda'=>$this->menuIzquierda,
            'itemSelect'=>$this->itemSelect,
            'actionName'=>$this->actionName,
            'lang'=>$this->lang,
            'controllerName'=>$this->controllerName
            );
        echo $this->render('render/menuizq.phtml',$arrayOption); //vista rederizada para el menu izquierda ?>
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <div class="cnt_slide">
                    <div class="photo">	
                        <?php 
                        foreach($this->fotos as $foto)
                        {                            
                        ?>
                        <div id="" class="item">
                            <img src="<?php echo $this->baseUrl().'/history/'.$foto['nombreImgHistory'];?>" width="810" />
                        </div>
                        <?php } ?>
                    </div>
                    <div id="pager" class=""></div>
                </div>
                <p>
                    <?php echo $this->historia['contenidoHistory']?> 									
                </p>
                <a href="<?php echo $this->historia['linkHistory']?>">
                    <?php echo $this->historia['linkHistory']?> 
                </a>
            </div>
        </section>
    </div>
</div>