<div id="content" class="layout_fluid_inner">
    <div class="inside">
<?php 
            $arrayOption = array(
            'menuIzquierda'=>$this->menuIzquierda,
            'itemSelect'=>$this->itemSelect,
            'actionName'=>$this->actionName,
            'lang'=>$this->lang,
            'controllerName'=>$this->controllerName
            );
        echo $this->render('render/menuizq.phtml',$arrayOption); //vista rederizada para el menu izquierda ?>
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <?php
                foreach($this->listaRealisations as $index): ?>
                <article class="box_article">
                    <h2><?php echo strtoupper($index['titleRealisationsIdioma']); ?></h2>								
                    <img class="imgRight" src="/realisations/<?php echo $index['imagen']?>"/>
                    <p><?php echo $index['contenidoRealisationsIdioma'] ?></p>
                    <a href="#"	 class="more"><?php echo $index['link'] ?></a>				
                </article>
                <?php endforeach;?>
            </div>
        </section>
    </div>
</div>