
<div class="table_admin" >
<div class="table_admin_head" ></div>
<div class="table_admin_body" align="left">
<form id="usercreate" enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->getBaseUrl();?>/admin/user/create">
<table width="650" border="0" cellspacing="0" cellpadding="0" class="table_form">
 <thead>
  <tr>
    <th align="left" colspan="2" class="champs_obligatoires" ><?php echo $this->getTranslation('Los campos marcados con * son obligatorios'); ?></th>
  </tr>
  <tr>
  	<td  height="5" colspan="2"></td>
  </tr>
</thead>
<tbody>
    <tr>
        <td align="left" width="20%" ><?php echo $this->getTranslation('Nombre'); ?>*</td>
        <td align="left" width="80%"><input type="text" name="first_name" id="first_name" value="" size="40" class="required" /></td>
    </tr>
     <tr>
        <td align="left" width="20%" ><?php echo $this->getTranslation('Apellidos'); ?>*</td>
        <td align="left" width="80%"><input type="text" name="last_name" id="last_name" value="" size="40"  class="required"/></td>
    </tr>
     <tr>
        <td align="left" width="20%" ><?php echo $this->getTranslation('Email'); ?>*</td>
        <td align="left" width="80%"><input type="text" name="email" id="email" value="" size="40"  /></td>
    </tr>
     <tr>
        <td align="left" width="20%" ><?php echo $this->getTranslation('Tipo'); ?>*</td>
        <td align="left" width="80%"><?php echo $this->SelectAdminRole('role',''); ?></td>
    </tr>
     <tr>
        <td align="left" width="20%" ><?php echo $this->getTranslation('Contraseña'); ?>*</td>
        <td align="left" width="80%"><input type="password" name="password" id="password" value=""  /></td>
    </tr>
     <tr>
        <td align="left" width="20%" ><?php echo $this->getTranslation('Confirmar contraseña'); ?>*</td>
        <td align="left" width="80%"><input type="password" name="password_confirm" id="password_confirm" value="" /></td>
    </tr>
</tbody>
<tfoot>
<tfoot>
<tr >
    <td align="right" colspan="2" >
        <input type='submit'  value='<?php echo $this->getTranslation('Enviar'); ?>'  >
        <input type=button onclick="location.href='<?php echo $this->getBaseUrl()?>/admin/user/';" value='<?php echo $this->getTranslation('Cancelar'); ?>' name='cancel'/>
   
    </td>
</tr>
</tfoot>
</table>
   </form>
</div>
<div class="table_admin_foot" ></div>
</div>
<?php 
   $this->jQuery()->onLoadCaptureStart();
?>
         $("#usercreate").validate({
		rules: {
                        email: {
				required: true,
				email: true,
				remote: "<?php echo $this->getBaseUrl()?>/admin/user/emailvalider"
			},
			password: {
				required: true,
				minlength: 5
			},
			password_confirm: {
				required: true,
				minlength: 5,
				equalTo: "#password"
			}

		},
		messages: {
                        email: {
				required: "<?php echo $this->getTranslation('El campo es obligatorio'); ?>",
				minlength: jQuery.format("Introduzca al menos {0} caracteres"),
				remote: jQuery.format("{0} existe deja")
			},
			password: {
				required: "<?php echo $this->getTranslation('Por favor, ingrese su contraseña'); ?>",
				minlength: "<?php echo $this->getTranslation('Su contraseña debe tener al menos 5 caracteres'); ?>"
			},
			password_confirm: {
				required: "<?php echo $this->getTranslation('Por favor, ingrese su contraseña'); ?>",
				minlength: "<?php echo $this->getTranslation('Su contraseña debe tener al menos 5 caracteres'); ?>",
				equalTo: "<?php echo $this->getTranslation('Por favor, introduzca la misma contraseña que el anterior'); ?>"
			}
		}
	});
<?php 
    $this->jQuery()->onLoadCaptureEnd(); 
?>