<div id="content" class="layout_fluid_inner">
    <div class="inside">
        <?php echo $this->render('render/menuizq.phtml'); //vista rederizada para el menu izquierda ?>
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <?php 
                foreach($this->dataSite as $index=>$data):?>
                <h2><?php echo $index; ?></h2>
                
                <div class="cf">
                    <?php foreach($data as $index2):?>
                    <div class="box_border box_lienamis">
                        <h3><?php echo $data['nombreSite']?></h3>
                        <a href="<?php echo $data['urlSite']?>"><?php echo $data['urlMostrar']?></a>
                    </div>
                    <?php endforeach; ?>
                </div>
                <?php endforeach; ?>
            </div>					
        </section>
    </div>
</div>