
<div id="content" class="layout_fluid_inner">
    <div class="inside">
        <?php echo $this->render('render/menuizq.phtml'); //vista rederizada para el menu izquierda ?>
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <p>En 2008, Elisabeth lance son blog, Elisabeth de Feydeau’s News, où elle partage son avis et ses connaissances 
                    de femme et d’experte sur les tendances olfactives.</p>	
                <a href="#">http://elisadefeydeau.wordpress.com</a>

                <div class="cf cnt_item">
                    <a href="/blog/img_elisafey_bio_2.jpg" class="item zoom">
                        <img class="" src="/blog/img_foto1_elisafey.jpg" width=""/>										
                    </a>
                    <a href="/blog/img_elisafey_bio_1.jpg" class="item zoom">
                        <img class="" src="/blog/img_foto2_elisafey.jpg" width=""/>										
                    </a>					
                </div>
            </div>	
        </section>    
    </div>
</div>