
<div id="content" class="layout_fluid_inner">
    <div class="inside">
        <?php echo $this->render('render/menuizq.phtml'); //vista rederizada para el menu izquierda ?>
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">								

                <div class="cf"	>
                    <div class="row odd">
                        <div class="row_inner">
                            <div class="detail">
                                <h3>2011</h3>												
                                <p>
                                    Les Parfums : dictionnaire, anthologie, histoire <br/>
                                    Ouvrage complet<br/>
                                    (éditions R. Laffont) 
                                </p>
                            </div>
                            <div class="photo">
                                <a href="#">
                                    <img class="" src="/imgOuverages/thums_img_elisafey_ouvrages.jpg" width=""/>	
                                </a>
                            </div>
                        </div>
                        <div class="row_slide">
                            <div class="detail">
                                <p>
                                    Les Parfums : dictionnaire, anthologie, histoire <br/>
                                    Ouvrage complet<br/>
                                    (éditions R. Laffont)													
                                </p>
                                <a href="#" class="">aqui</a>
                            </div>
                            <div class="photo">
                                <img class="" src="/imgOuverages/img_elisafey_ouvrages.jpg" width=""/>	
                            </div>
                        </div>
                    </div>
                    <div class="row even">	
                        
                        <div class="row_inner">
                            <div class="detail">
                                <h3>2011</h3>												
                                <p>
                                    Les Parfums : dictionnaire, anthologie, histoire <br/>
                                    Ouvrage complet<br/>
                                    (éditions R. Laffont) 
                                </p>

                            </div>
                            <div class="photo">
                                <a href="#">
                                    <img class="" src="/imgOuverages/thums_img_elisafey_ouvrages.jpg" width="278"/>	
                                </a>
                            </div>
                        </div>
                        
                        <div class="row_slide">
                            <div class="detail">
                                <p>
                                    Les Parfums : dictionnaire, anthologie, histoire <br/>
                                    Ouvrage complet<br/>
                                    (éditions R. Laffont)													
                                </p>
                                <a href="#" class="">aqui</a>
                            </div>
                            <div class="photo">
                                <img class="" src="/imgOuverages/img_elisafey_ouvrages.jpg" width="278"/>	
                            </div>
                        </div>
                        
                    </div>


                </div>

            </div>	
        </section>
    </div>
</div>