
<div id="content" class="layout_fluid_inner">
    <div class="inside">
        <?php echo $this->render('render/menuizq.phtml'); //vista rederizada para el menu izquierda ?>
<!--        <aside id="aside">

            <ul class="lst_aside selected">														
                <li><a class="" href="#">Biographie</a></li>									
                <li><a class="selected" href="#">Ouvrages</a></li>									
                <li><a class="" href="#">Réalisations</a></li>									
                <li><a class="" href="#">Blog et Photos</a></li>
            </ul>			



        </aside>-->
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">								
                <div class="cf">
                    <h2>Elisabeth de Feydeau</h2>
                    <div class="inside">
                        <div class="cnt_slide_bio">
                            <div class="photo">										
                                <div class="item">
                                    <img class="" src="/biographie/img_elisafey_bio_1.jpg" width=""/>	
                                </div>
                                <div class="item">
                                    <img class="" src="/biographie/img_elisafey_bio_2.jpg" width=""/>	
                                </div>
                            </div>
                            <div id="pager" class=""></div>
                        </div>
                        <p>Passionnée de littérature et d’Histoire, Elisabeth de Feydeau étudie à l’université Paris IV-Sorbonne, où elle obtient en 1997 son doctorat d’Histoire Contemporaine, salué à l’unanimité par le jury. Elle avait choisi d’intituler sa thèse « De l’Hygiène au Rêve : l’industrie française du parfum, de 1830 à 1945 ». </p>

                        <p>Elle est d’abord responsable des affaires culturelles chez Chanel et Bourjois, où elle met en place et gère le conservatoire. Elisabeth y acquiert la connaissance des matières premières de la parfumerie, grâce à une formation olfactive au sein du Laboratoire des parfums. </p>

                        <p>Ses atouts et connaissances l’encouragent à créer sa propre société de conseil en développement olfactif et culturel. Arty Fragrance voit alors le jour, redéfinissant les valeurs et collaborant au design olfactif, à la communication ou à la formation pour des noms prestigieux de la parfumerie. </p>

                        <p>Auteure de plusieurs ouvrages sur le luxe et le parfum, Elisabeth met également en scène diverses expositions, anime ateliers et conférences à travers le monde. Au fil des années, les sens et qualités de cette historienne spécialiste du parfum l’ont placée au cœur de ce métier, investie dans les domaines les plus divers. Sa profonde compréhension de l’Histoire et son sens olfactif lui permettent d’analyser le chemin parcouru afin de comprendre les aspirations modernes et d’anticiper les tendances : un savoir faire qu’elle transmet depuis 1998 aux étudiants et futurs parfumeurs des groupes Essec et Isipca. 

                        <p>En 2010, Elisabeth de Feydeau elle est nommée Chevalier des Arts et des Lettres par le Ministre de la Culture, Frédéric Mitterrand. 
                            La même année, elle est intronisée « Dame de la Jurade » à Saint Émilion.ms : dictionnaire, anthologie, histoire » (aux éditions R. Laffont, collections Bouquins). </p>

                    </div>

                </div>
            </div>	
        </section>
    </div>
</div>