
<div id="content" class="layout_fluid_inner">
    <div class="inside">
        <?php echo $this->render('render/menuizq.phtml'); //vista rederizada para el menu izquierda ?>
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <article class="box_article">
                    <h2>Marchés de Noël 2011 à Versailles</h2>								
                    <img class="imgLeft" src="img/temp/img_noticia_1.jpg"/>
                    <p>Venez découvrir nos collections au Marché de Noël  à Versailles</p>
                    <ul>
                        <li>Lieu</li>
                        <li>Trianon Palace</li>
                        <li>1 boulevard de la Reine</li>
                        <li>78000 Versailles</li>
                    </ul>

                    <p>Du 03 au 24 décembre 2011 inclus - De 14H00 à 20H00 
                        Les mercredis, samedis et dimanches et le vendredi 23 décembre 2011</p>							
                </article>
                <article class="box_article">
                    <h2>Titre news 2 2010</h2>										

                    <p>Allumer la mèche, attendre que la cire devienne liquide (au minimum 10 mn), éteindre la bougie.</p>

                    <p>Verser l'huile fondue dans la paume de la main (après contrôle de la température), 
                        (l'huile sera tiède mais non brûlante) et masser.</p>

                    <p>Avant la 1ère utilisation, tester sur une petite zone de peau pour éviter tout risque 
                        d’allergie. Rincer le produit à l’eau s’il y a  apparition de rougeurs ou démangeaisons.</p>

                </article>
                <article class="box_article">
                    <h2>Titre news 2 2010</h2>								
                    <img class="imgLeft" src="img/temp/img_noticia_2.jpg"/>
                    <p>Allumer la mèche, attendre que la cire devienne liquide (au minimum 10 mn), éteindre la bougie.</p>

                    <p>Verser l'huile fondue dans la paume de la main (après contrôle de la température), 
                        (l'huile sera tiède mais non brûlante) et masser.</p>

                    <p>Avant la 1ère utilisation, tester sur une petite zone de peau pour éviter tout risque 
                        d’allergie. Rincer le produit à l’eau s’il y a  apparition de rougeurs ou démangeaisons.</p>
                </article>
                <article class="box_article">
                    <h2>Marchés de Noël 2011 à Versailles</h2>								
                    <p>Allumer la mèche, attendre que la cire devienne liquide (au minimum 10 mn), éteindre la bougie.</p>

                    <p>Verser l'huile fondue dans la paume de la main (après contrôle de la température), 
                        (l'huile sera tiède mais non brûlante) et masser.</p>

                    <p>Avant la 1ère utilisation, tester sur une petite zone de peau pour éviter tout risque 
                        d’allergie. Rincer le produit à l’eau s’il y a  apparition de rougeurs ou démangeaisons.</p>					
                </article>							
            </div>
        </section>
    </div>
</div>