<table width="100%" border="0" cellpadding=0 cellspacing=0>
    <tr>
    <td>
        	<?php echo $this->getTranslation('Versión actual') . ':';?> <strong>
<?php
$config = Zend_Registry::get('config');
$siteVersions = $config->language->translations;
$lang = $this->currentVersion;
$data=$this->getRequest();
$settings = new Model_SiteSettings();
$default_language=$settings->get('default_language');
$lang=($data->version?$data->version:$default_language);
echo $this->getTranslation($siteVersions->$lang);
?>
</strong>
&nbsp;&nbsp;&nbsp;
<?php if ($siteVersions) { ?>
<?php echo $this->getTranslation('Idioma disponible')?>:
<?php } ?>

</td>
   <td>
   <?php if ($siteVersions) {
	$uri = new Altimea_Uri();
             $base = $uri->toString();
		     $newrl=$uri->cleanUriVersion($base);
	 ?>
<select name="lang_code"  id="lang_code"  onchange="location.href='<?php echo $newrl?>/version/'+this.value">
<?php
foreach ($siteVersions as $key => $version) {
	$select='';
    $version = $this->getTranslation($version);
    if ($key == $lang) {
		$select='selected="selected"';
    }
    echo '<option value="'.$key.'" title="'.$this->getBaseUrl().'/images/flags/'.$key.'.png" '.$select.'  >' . $version . '</li>';
}
?>
</select>
<?php } 
?>
       </td>
   </tr>
</table>


