<div id="content" class="layout_fluid_inner">
    <div class="inside">
        <?php 
            $arrayOption = array(
            'menuIzquierda'=>$this->menuIzquierda,
            'itemSelect'=>$this->itemSelect,
            'actionName'=>$this->actionName,
            'lang'=>$this->lang,
            'controllerName'=>$this->controllerName
            );
        echo $this->render('render/menuizq.phtml',$arrayOption); //vista rederizada para el menu izquierda ?>
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <p>Ac, lorem porttitor enim nec porttitor vel nisi, auctor turpis pellentesque risus.
                    Purus velit non! Nascetur tempor pellentesque nunc nunc? Pellentesque. Arcu mattis rhoncus,
                    et augue ultricies cursus amet sed sit risus arcu dis enim nascetur. Ac montes. 
                    Cursus integer eu ut. Dolor parturient sed nec platea dignissim? Augue facilisis nascetur 
                    mattis in et placerat in ac, eu duis dignissim, magna et in, odio, a scelerisque in nec 
                    lectus urna, mauris vel, egestas dapibus augue, et. Integer tempor et tempor massa nascetur
                    lundium dictumst, lacus adipiscing sit et nascetur enim nunc vel tincidunt dictumst platea 
                    amet penatibus enim, duis amet penatibus mauris tincidunt sit turpis, pulvinar integer placerat
                    lacus nisi ultricies placerat in enim, porta auctor magna! Amet. Aliquet, dictumst.</p>

                <p>Nisi? Porta etiam, pulvinar, ultricies amet dignissim vel? Egestas a dolor. Mid in? Pulvinar,
                    scelerisque, velit in, nunc adipiscing urna mattis lorem lundium, integer placerat eu proin, 
                    proin in? Sit a? Rhoncus. Tempor! Elementum ultrices. Pid platea massa, parturient porta lundium
                    lectus ac! Magna! Ac. Montes porttitor nisi? Turpis est diam lectus sit, penatibus, scelerisque 
                    dignissim scelerisque parturient vel hac tincidunt, non, et purus! Penatibus vel dictumst turpis.
                    Lorem facilisis lorem, lundium eros! Purus amet porttitor elementum, diam non mid, ultrices, 
                    nunc? Cras. Cursus egestas amet? Elit etiam magna lacus duis diam lacus sed magnis lacus est integer,
                    nec et sit nunc in, a rhoncus turpis turpis nascetur aenean dolor adipiscing? Cum montes, elementum
                    integer magna enim, integer et.</p>

                <p>Et enim dapibus adipiscing nec turpis vel ultrices cras nec montes, lectus enim tincidunt et ut 
                    aenean aliquet magnis, dictumst, natoque sed sociis, porttitor cursus, cras sit rhoncus aliquet, 
                    ultrices, et, aliquet? Urna? Mid sed rhoncus magna turpis turpis! A? Eu, vut amet augue, ut cras vel. 
                    Enim duis platea a aliquam augue. Adipiscing penatibus massa, lectus ultricies integer, elementum 
                    purus risus scelerisque vel adipiscing duis et est mid turpis aliquet augue adipiscing, auctor et 
                    tempor penatibus in turpis cras etiam aliquet non, placerat odio lundium, montes dolor nascetur, 
                    habitasse mauris vel augue nisi tristique diam scelerisque turpis ac, lectus adipiscing, nisi lectus
                    pulvinar scelerisque porttitor tincidunt, massa penatibus, adipiscing? Penatibus mattis vut. 
                    Turpis porta mus phasellus sed lundium.</p>
            </div>
        </section>
    </div>
</div>