<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title><?php echo $this->getTranslation('WEB Administration');?></title>
<link rel="stylesheet" type="text/css" media="screen"
      href="<?php echo $this->getBaseUrl();?>/templates/admin/default/styles/admin.css" />
            <style type="text/css">
	  fieldset{
		  width:67%;		  
	  }
	  fieldset p{
		  margin: 0px 0;			  
	  }
	  </style>
</head>
<body style="background: #ffffff url(<?php echo $this->getBaseUrl();?>/templates/admin/default/images/bg_login01.gif) repeat-y top center;">
<div id="login_body" align="center">
    <div id="login_content">
   <img src="<?php echo $this->getBaseUrl();?>/images/px.gif" alt="" width='200' height='10' border="0" />
 	<form action="" method="post"  class="form">
      <div><?php echo $this->getTranslation('Vous avez oublié votre mot de passe?');?></div>
		<table width="230" border="0" cellspacing="2" cellpadding="2">
    <tr>
      <td><?php echo $this->getTranslation('Email');?>
        </td>
      <td align="right"><input type="text" name="email" id="email" value="" maxlength="100" size="20" class="login"/>
        </td>
    </tr>
    <tr>
      <td colspan="2">
        <div style="float:left; width:70%;">
            <a class="mdp" href="<?php echo $this->getBaseUrl();?>/admin/">&laquo; <?php echo $this->getTranslation('Se connecter');?></a>
        </div>
        <div style="float:left; width:30%;" align="right">
          <input type="submit" name="access" value="<?php echo $this->getTranslation('Validar');?>" />
        </div>
      </td>
      </tr>
</table>
        </form>
		<?php echo $this->RenderAlert();?>
    </div>
	
</div>

</body>
</html>