<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <title>
            WEB Administration        
        </title>
        <link href="/b/styles/layout.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/b/styles/text.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/b/styles/nav.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/b/styles/style.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/b/styles/form.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/styles/datePicker.css" media="screen" rel="stylesheet" type="text/css" />       
        <link href="/styles/adminForms.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/styles/filetree.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/styles/menutree.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/styles/spreadsheet.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/styles/sortable.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/styles/ThickBox.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/styles/styles.css" media="screen" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="/scripts/jquery.js"></script>
        <script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
        <script type="text/javascript" >
            var getBaseUrl="";
        </script>
    </head>
    <body>
        <div id="page">
            <div  class="header-top">Langue 
                <a href="/admin/site/lang/version/fr" class="adminchangelanguage">
                    <img src="/images/flags/fr.png" alt="" border="0" align="absmiddle" />
                </a>  
                <a href="/admin/site/lang/version/es" class="adminchangelanguage">
                    <img src="/images/flags/es.png" alt="" border="0" align="absmiddle" />
                </a> 
                <a href="/admin/site/lang/version/de" class="adminchangelanguage">
                    <img src="/images/flags/de.png" alt="" border="0" align="absmiddle" />
                </a>  
                <a href="/admin/site/lang/version/jp" class="adminchangelanguage">
                    <img src="/images/flags/jp.png" alt="" border="0" align="absmiddle" />
                </a> 
                Utilisateur actuel: admin  admin  Tipo: superadmin
                <a href='/admin/auth/logout/'>Déconnecter</a> 
            </div>
            <div id="header">
                <ul id="adminMenu">
                    <li class="logo">
                        <a id="homeLink" href="">&nbsp;&nbsp;</a></li>
                    <li class="cuentas"><a id="homeLink" href="/admin/user">Comptes&nbsp;&nbsp;</a></li><li class="configuracion"><a id="siteLink" href="/admin/site/index">Configuration&nbsp;&nbsp;</a></li><li class="publicidad"><a class="selected" id="moduleLink" href="/admin/module">Modules</a></li></ul>	   <div id="bar_top">
                  <!--<img src="/images/px.gif" alt="" width='2000' height='2' border="0" />-->
                </div>
            </div>
            <div id="pageShadow">
                <div id="pageInner" class="clearFix">
                    <table width="100%" cellspacing="0" cellpadding="0" border="0">
                        <tbody>
                            <tr>
                                <td valign="top" height="500" class="sidebar">
                                    <?php echo $this->render('menuadmin.phtml', array('baseUrl' => $this->baseUrl())); ?>
                                </td>
                                <!-- container-->

                                <?php echo $this->layout()->content ?>

                                <!-- container -->
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div id="footer"></div>
        </div>
        <link rel="stylesheet" href="/styles/cloner.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/scripts/msdropdown/dd.css" type="text/css" media="screen" />
        <script type="text/javascript" src="/scripts/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="/scripts/jquery-ui-1.8.custom.min.js"></script>
        <script type="text/javascript" src="/scripts/jquery.ifixpng/jquery.ifixpng.js"></script>
        <script type="text/javascript" src="/scripts/jquery.media/jquery.media.js"></script>
        <script type="text/javascript" src="/scripts/jquery.validate.js"></script>
        <script type="text/javascript" src="/scripts/jquery.metadata.js"></script>
        <script type="text/javascript" src="/scripts/jquery.addfield.js"></script>
        <script type="text/javascript" src="/scripts/js_admin.js"></script>
        <script type="text/javascript" src="/scripts/msdropdown/js/jquery.dd.js"></script>
        <script type="text/javascript" src="/scripts/jquery.qtip-1.0.0-rc3.js"></script>
        <script type="text/javascript" src="/scripts/jquery.tablednd_0_5.js"></script>
        <script type="text/javascript" src="/scripts/admin-dnd.js"></script>
        <script type="text/javascript" src="/scripts/jquery.cookie.js"></script>
        <script type="text/javascript" src="/scripts/jquery.ajaxfileupload.js"></script>

        <script type="text/javascript">
            //<![CDATA[
            $(document).ready(function() {
                //estado
                $('a.status-module').click(function(e){
                    e.preventDefault();
                    var objeto=this;

                    var msg='';
                    var cambio='';
                    var alt='';

                    if($(objeto).children('img').attr('alt')=='enabled.gif'){
                        msg='Souhaitez-vous ne pas montrer ce module ?';
                        cambio='Montrer ce module';
                        alt='disabled.gif';
                    }
                    else{
                        msg='Souhaitez-vous montrer ce module ?';
                        cambio='Ne pas montrer ce module';
                        alt='enabled.gif';
                    }


                    if(confirm(msg)){
                        $.post(objeto.href,function(data){
                            $(objeto).children('img').attr('src',data);
                            $(objeto).children('img').attr('alt',alt);
                            objeto.title=cambio;
                            location.reload(true)
                        });
                    }

                });


                $('a.status-module').each(function(){
                    var msg='';
                    var objeto=this;
                    if($(objeto).children('img').attr('alt')=='enabled.gif'){
                        msg='Ne pas montrer ce module';
                    }
                    else{
                        msg='Montrer ce module';
                    }
                    this.title=msg;
                });
                $('a.status-config').each(function(){
                    var msg='';
                    var objeto=this;
                    if($(objeto).children('img').attr('alt')=='process_accept.png'){
                        msg='Installer ce module';
                    }
                    else{
                        msg='Enlever le module';
                    }
                    this.title=msg;
                });
                $('a.status-config').click(function(e){
                    /*e.preventDefault();*/
                    var msg=$(this).attr('title');
                    if(confirm(msg)){
                        return true;
                    }else{
                        return false;
                    }


                });

                $("label.error").css({'display' : 'none'});
                $.metadata.setType("attr", "validate");
                $("#formupload").validate();

                var updatemodules = $.cookie('updatemodules');
                if (updatemodules)
                    $("#updatemodules").css({'display' : updatemodules == 'none' ? 'block':'none'});
                var listmodules = $.cookie('listmodules');
                if (listmodules)
                    $("#listmodules").css({'display' : listmodules == 'none' ? 'block':'none'});
                var hooksposition = $.cookie('hooksposition');
                if (hooksposition)
                    $("#hooksposition").css({'display' : hooksposition == 'none' ? 'block':'none'});
    
                $('#menumodules div').hide();
                $('#menumodules h3').removeClass('select').css({'cursor':'pointer', 'display':'block'});
                /*
                $.get(getBaseUrl+'/admin/module/getaccodion/', function(data){
                                $('#' + data).next().show();
                                $('#' + data).addClass('select');
                });
                 */
                var data=1;
                $('#' + data).next().show();
                $('#' + data).addClass('select');


                $('.modulecategory').click(function(){
                    var checkElement = $(this).next();
                    if((checkElement.is('div')) && (!checkElement.is(':visible'))) {
                        $('#menumodules div:visible').slideUp('normal');
                        checkElement.slideDown('normal');
                        $.ajax({
                            type: "POST",
                            url: getBaseUrl+'/admin/module/setaccodion/',
                            data: "id="+this.id
                        });
                    }
                });

    
                $(".message_box").bind("click",function(){
                    $(this).fadeOut("slow");
                });

                $('a.delete').bind('click',function(){
                    var answer = confirm('Etes-vous sûr de vouloir supprimer l\'enregistrement ?');
                    if(!answer){return false;}
                });
                //estado
                $('a.status').click(function(e){
                    e.preventDefault();
                    var objeto=this;

                    var msg='';
                    var cambio='';
                    var alt='';

                    if($(objeto).children('img').attr('alt')=='enabled.gif'){
                        msg='Ne pas montrer cet enregistrement';
                        cambio='Montrer cet enregistrement';
                        alt='disabled.gif';
                    }
                    else{
                        msg='Montrer cet enregistrement';
                        cambio='Ne pas montrer cet enregistrement';
                        alt='enabled.gif';
                    }


                    if(confirm(msg)){
                        $.post(objeto.href,function(data){
                            $(objeto).children('img').attr('src',data);
                            $(objeto).children('img').attr('alt',alt);
                            objeto.title=cambio;
                        });
                    }

                });

                $('a.status').each(function(){
                    var msg='';
                    var objeto=this;
                    if($(objeto).children('img').attr('alt')=='enabled.gif'){
                        msg='Ne pas montrer cet enregistrement';
                    }
                    else{
                        msg='Montrer cet enregistrement';
                    }
                    this.title=msg;
                });
                ///////////////////////////
    
    
                $('a.home').click(function(e){
                    e.preventDefault();
                    var objeto=this;
        
                    var msg='';
                    var cambio='';
                    var alt='';
        
                    if($(objeto).children('img').attr('alt')=='marcado.gif'){
                        msg='Souhaitez-vous ne pas publier cet enregistrement ?';
                        cambio='Publier cet enregistrement';
                        alt='desmarcado.gif';
                    }
                    else{
                        msg='Souhaitez-vous publier cet enregistrement ?';
                        cambio='Ne pas publier cet enregistrement';
                        alt='marcado.gif';
                    }
        
        
                    if(confirm(msg)){
                        $.post(objeto.href,function(data){
                            $(objeto).children('img').attr('src',data);
                            $(objeto).children('img').attr('alt',alt);
                            objeto.title=cambio;
                        });
                    }
        
                });

    
    
                $('a.home').each(function(){
                    var msg='';
                    var objeto=this;
                    if($(objeto).children('img').attr('alt')=='enabled.gif'){
                        msg='Ne pas publier cet enregistrement';
                    }
                    else{
                        msg='Publier cet enregistrement';
                    }
                    this.title=msg;
                });
    
    
                /////////////
    
                //status profesional
                $('a.statusp').click(function(e){
                    e.preventDefault();
                    var objeto=this;

                    var msg='';
                    var cambio='';
                    var alt='';

                    if($(objeto).children('img').attr('alt')=='enabled.gif'){
                        msg='Etes-vous sûr de ne pas vouloir valider cet enregistrement ?';
                        cambio='Envoyer cet enregistrement';
                        alt='disabled.gif';
                    }
                    else{
                        msg='Souhaitez-vous valider cet enregistrement ?';
                        cambio='N\'est pas possible valider cet enregistrement';
                        alt='enabled.gif';
                    }


                    if(confirm(msg)){
                        $.post(objeto.href,function(data){
                            $(objeto).children('img').attr('src',data);
                            $(objeto).children('img').attr('alt',alt);
                            objeto.title=cambio;
                        });
                    }

                });

                $('a.statusp').each(function(){
                    var msg='';
                    var objeto=this;
                    if($(objeto).children('img').attr('alt')=='enabled.gif'){
                        msg='Ne pas valider cet enregistrement';
                    }
                    else{
                        msg='Valider cet enregistrement';
                    }
                    this.title=msg;
                });

            });
            //]]>

        </script>
        <div class="ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all ui-helper-hidden-accessible" id="ui-datepicker-div"></div>                        
    </body>
</html>

