<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<!--[if lt IE 7]> <html lang="es-es" class="no-js ie6"> <![endif]-->
<!--[if IE 7]>    <html lang="es-es" class="no-js ie7"> <![endif]-->
<!--[if IE 8]>    <html lang="es-es" class="no-js ie8"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" xmlns:fb="http://ogp.me/ns/fb#"> 
    <!--<![endif]-->
<head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headStyle() ?>
<link rel="stylesheet/less" type="text/css" href="/f/css/screen.less?id=1">
<script src="/f/js/less-1.1.5.min.js" type="text/javascript"></script>
<script src="/f/js/jquery.js" type="text/javascript" charset="utf-8"></script>
<script src="/f/js/jquery.cycle.all.js" type="text/javascript" charset="utf-8"></script>
<script src="/f/js/main.js" type="text/javascript" charset="utf-8"></script>
        <?php echo $this->headLink() ?>
<!--[if lt IE 9]>
  <script src="/f/js/html5.js"></script>
<![endif]-->
<!--[if lt IE 10]>
    <link rel="stylesheet" href="/f/css/ieonly.css" type="text/css" media="screen" />
<![endif]-->
</head>
<body id="" class="lyt_home" onLoad="">
	<div class="wrapper">
		<div class="wrapper_l">
		<div class="wrapper_r">
			<div class="wrapper_inner">
				<div id="main_header" class="layout_fluid">		
					<header id="header" class="cf layout_fluid_inner">
						<h1 class="logo"><a href="#">ARTY Fragance</a></h1>	
					</header>
				</div>
				
				<div id="main_menu" class="layout_fluid ">
					<div id="menu" class="layout_fluid">
						<div class="layout_fluid menu_l">
							<div class="layout_fluid menu_r">
								<div class="layout_fluid_inner menu_m">
									<div class="layout_fluid_inner menu_m_inner">
									
										<nav id="nav">
											<ul>
                                                                                            <?php echo $this->render('frontmenu.phtml',array('menuSup'=>$this->menuSup));?>
<!--												<li><a href="#">Accueil</a></li>
												<li><a href="#">Arty Fragrance</a></li>
												<li><a href="#">Collections</a></li>
												<li><a href="#">Elisabeth de Feydeau</a></li>
												<li><a href="#">Mécénat Versailles</a></li>
												<li><a href="#">Presse</a></li>
												<li><a href="#">Points de vente </a></li>
												<li><a href="#">Points de vente </a></li>-->
											</ul>
										</nav>
									
									</div>							
								</div>
							</div>
						</div>
					
					
				
					</div>
				</div>
				

				<div id="main_slide" class=" layout_fluid">
					<div id="slide" class="item layout_fluid_inner" >	
						<div class="overview">
							<div id="" class="item_slide">
								<img src="/f/img/temp/img_slide.jpg" />
							</div>
							<div id="" class="item_slide">
								<img src="/f/img/temp/img_slide.jpg" />
							</div>		
						
						</div>
					</div>		
				</div> 
				
				
				
				
				
				
				<div id="main_content" class="layout_fluid ">
					<div id="content" class="layout_fluid_inner">
						<div class="inside cf">
												
							<div class="box box_item_home">
								<h2>
									<span>Nouveautés</span>
								</h2>
								<div class="cf">	
									<div class="box_l">
										<img src="/f/img/temp/img_item_home_1.jpg" />
									</div>
									<div class="box_r">
										<h3>Coffret Saint Valentin</h3>
										<p>Du portugais « barocco », le terme baroque désigne la forme irrégulière d’une perle.
										Dès la fin de la Renaissance, il décrit un contraste artistique fort, mêlant l’ombre à la
										lumière. En sculpture, peinture, littérature mais surtout en musique, l’art baroque est 
										fait de paradoxes et d’exubérance.</p>
									</div>
									
								</div>
								<div class="box_b">
									<a href="#">+ En savoir plus</a>								
								</div>
							</div>
							
							<div class="box box_item_home last">
								<h2>
									<span>Actualités</span>
								</h2>
								<div class="cf">							
									<div class="box_l">
										<img src="/f/img/temp/img_item_home_2.jpg" />
									</div>
									<div class="box_r">
										<h3>Marchés de Noël 2011 à Versailles</h3>
										<p>Venez découvrir nos collections au Marché de Noël  à Versailles</p>
										<ul>
											<li>Lieu</li>
											<li>Trianon Palace</li>
											<li>1 boulevard de la Reine</li>
											<li>78000 Versailles </li>
										</ul>
										<p>Du 03 au 24 décembre 2011 inclus - De 14H00 à 20H00 
										Les mercredis, samedis et dimanches et le vendredi 23 </p>									
										
									</div>
								</div>	
								<div class="box_b">									
									<a href="#">+ Lire la suite</a>	
								</div>
							</div>
							
						</div>
				
					</div>
				</div>
				
				<div id="main_footer" class="layout_fluid">
					<footer id="footer" class="cf layout_fluid_inner">
						<p class="copyright">
							© Arty Fragrance  2011 Tous droits réservés
						</p>
						<ul class="lst_footer lst_recommend">
							<li><a class="fb first" href="#"></a></li>
							<li><a class="selected" href="#">Blog</a></li>
							<li><a href="#">Recommander le site</a></li>
						</ul>
						<ul class="lst_footer lst_credits">
							<li><a href="#">Liens amis </a></li>
							<li><a href="#">Crédits </a></li>
							<li><a href="#">Mentions légales</a></li>
						</ul>
						<ul class="lst_footer lst_language">
							<li><a href="#">English version</a></li>
						</ul>
						
						
					</footer>
				</div>
			
			</div>
		</div>
		</div>
	</div>
	<div class="wrapper_b">
	</div>
</body>
</html>
        
        
    <?php //echo $this->layout()->content ?>
        
    <?php //echo $this->render('frontfooter.phtml',array('menuFooter'=>$this->menuFooter));?>    
