<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" xmlns:fb="http://ogp.me/ns/fb#">
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
    </head>
    
    <body id="index">
        
    <?php echo $this->render('frontmenu.phtml',array('menuSup'=>$this->menuSup));?>
        
    <?php echo $this->layout()->content ?>
        
    <?php echo $this->render('frontfooter.phtml',array('menuFooter'=>$this->menuFooter));?>    
        
    </body>

</html>