<div id="sidebar" class="column">
    <h2 class="top"></h2><div class="columnBody">
        <div id="menumodules">
            <h3 style="cursor: pointer; display: block;" id="1" class="modulecategory">Administrador</h3>
            <div style="display: block;">  
                <ul class="padding-10 ">

                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/index/menusuperior/idMenu/1' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Menu Superior
                            </a>
                        </span>
                    </li>
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/index/menufooter/idMenu/2' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Footer 1
                            </a>
                        </span>
                    </li>
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/index/menufooter/idMenu/3' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Footer 2
                            </a>
                        </span>
                    </li>
                </ul>

            </div>
            <h3 style="cursor: pointer; display: block;" id="2" class="modulecategory">Árticulos</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">

                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/index/accueil/idMenu/1' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">accueil
                            </a>
                        </span>
                    </li>
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/fragance/' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Arty Fragance
                            </a>
                        </span>
                    </li>

                </ul>

            </div>
            <h3 style="cursor: pointer; display: block;" id="3" class="modulecategory">Collections</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">

                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/index/collections/idMenu/3' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon" />Collections
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
            <h3 style="cursor: pointer; display: block;" id="4" class="modulecategory">Points de vente</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/pointventa/index/idMenu/7' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Points de vente</img>
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/paises' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Paises
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/ciudades' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Ciudad
                            </a>
                        </span>
                    </li>
                </ul>

            </div>
            <h3 style="cursor: pointer; display: block;" id="5" class="modulecategory">Sites</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">

                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/sites' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Sites
                            </a>
                        </span>
                    </li>

                </ul>

            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Utilitarios</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">

                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '#' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Name
                            </a>
                        </span>
                    </li>

                </ul>

            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Elisabeth de Feydeau</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/elisabeth-de-feydeau' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Biographie
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/elisabeth-de-feydeau/blog-et-photos' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Blog Et Photos
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/elisabeth-de-feydeau/ouvrages' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Ouvrages 
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/elisabeth-de-feydeau/admin-sub-menu' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Admin Sub Menu
                            </a>
                        </span>
                    </li>
                </ul>

            </div>
        </div
    </div>
</div>