<div id="sidebar" class="column">
    <h2 class="top"></h2><div class="columnBody">
        <div id="menumodules">
            <h3 style="cursor: pointer; display: block;" id="1" class="modulecategory">L'administrateur</h3>
            <div style="display: block;">  
                <ul class="padding-10 ">

                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/index/menusuperior/idMenu/1' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Un menu Supérieur
                            </a>
                        </span>
                    </li>
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/index/menufooter/idMenu/2' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Un pied de page 1
                            </a>
                        </span>
                    </li>
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/index/menufooter/idMenu/3' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Un pied de page 2
                            </a>
                        </span>
                    </li>
                </ul>

            </div>
            <h3 style="cursor: pointer; display: block;" id="3" class="modulecategory">des collections</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">

                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/collection/collections/idMenu/3' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon" />des collections
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
            <h3 style="cursor: pointer; display: block;" id="4" class="modulecategory">Points de vente</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/pointventa/index/idMenu/7' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Points de vente</img>
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/paises' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Pays
                            </a>
                        </span>
                    </li>
                </ul>

            </div>
            <h3 style="cursor: pointer; display: block;" id="5" class="modulecategory">Liens Amis</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">

                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/sites' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">endroits
                            </a>
                        </span>
                    </li>
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/sites/tipo-site' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Types d'endroit
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/sites/admin-page-liens-amis/' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Pagine de l'administrateur
                            </a>
                        </span>
                    </li>

                </ul>

            </div>

            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Elisabeth de Feydeau</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/elisabeth-de-feydeau' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Biographie
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/elisabeth-de-feydeau/blog-et-photos' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Blog Et Photos
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/elisabeth-de-feydeau/ouvrages' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Ouvrages 
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/elisabeth-de-feydeau/realisations' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">realisations 
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/elisabeth-de-feydeau/admin-sub-menu' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Sous-menu de l'administrateur
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/elisabeth-de-feydeau/admin-page' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Pagine de l'administrateur
                            </a>
                        </span>
                    </li>
                </ul>

            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Presse</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/presse' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Presse
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/presse/admin-page/' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Pagine de l'administrateur
                            </a>
                        </span>
                    </li>

                </ul>
            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Arty Fragance</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/actualites' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Actualites
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/nouveautes' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Nouveautes
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Recommander un endroit</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/sites/recomend-site' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Recommander un endroit
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/sites/admin-page' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Pagine de l'administrateur
                            </a>
                        </span>
                    </li>
                    
                </ul>
            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Credit</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/credit/' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Credit
                            </a>
                        </span>
                    </li>
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/credit/admin-page' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Pagine de l'administrateur
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Contact</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/contact/' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Contact
                            </a>
                        </span>
                    </li>
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/contact/admin-page' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Pagine de l'administrateur
                            </a>
                        </span>
                    </li>

                </ul>
            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Mentions Legales</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/legal' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Mentions Legales
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/legal/admin-page' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Pagine de l'administrateur
                            </a>
                        </span>
                    </li>
                    
                </ul>
            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Mecenat Versailles</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/mecenat-versailles' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Histoire
                            </a>
                        </span>
                    </li>
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/realisations' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Realisations
                            </a>
                        </span>
                    </li>
                    <li>
                        <span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/mecenat-versailles/admin-page' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Pagine de l'administrateur
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Demo Editor</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/demo-editor' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Demo Editor
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
            <h3 style="cursor: pointer; display: block;" id="6" class="modulecategory">Récupérer une clé</h3>
            <div style="display: none;">  
                <ul class="padding-10 ">
                    <li><span class="titulo">
                            <a href="<?php echo $this->baseUrl . '/admin/pass' ?>" class="link" style="cursor: pointer">
                                <img border="0" src="/images/icons/layout_sidebar.png" alt="" class="icon">Récupérer une clé
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>