<script type="text/javascript">
window.onload = function()
{
CKEDITOR.replace('contenidoCredit');
}
</script>
<td valign="top">
    <div id="centerPane">
        <div id="toolbar">
            <a class="modules" href="<?php //$this->baseUrl() ?>/admin/collection/index">Collections</a> &gt; <a class="actualités" href="<?php //$this->baseUrl() ?>/admin/collection/actualites/"><?php echo $this->params['action'] ?></a> &gt; Modifier               
            <div id="main">
                <!--   <h2 class="top"></h2>-->
                <div id="form">
                    <form id="frmDevenir" enctype="multipart/form-data" method="post" action="">
                        <div class="table_admin">                            
                            <div class="table_admin_head"></div>
                            <div align="center" class="table_admin_body">                                
                                <table cellspacing="0" cellpadding="0" border="0" width="100%" class="table_form">
                                    <tbody>
                                        <tr><th colspan="2">
                                            </th></tr>
                                        <tr>
                                            <td align="left" width="14%" valign="top">Description *</td>
                                            <td align="left" colspan="2">                                                
                                                <?php echo $this->form->contenidoCredit; ?>
                                            </td>
                                        </tr>

                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td align="right" valign="bottom" colspan="3">
                                                <?php echo $this->form->submit?>
                                                <input type="button" onclick="location.href='/admin/credit/newcredit/';" value="Annuler" name="cancel">
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <div class="table_admin_foot"></div>
                        </div>
                    </form>                
                </div>
            </div>
        </div>
</td>