<div id="content" class="layout_fluid_inner">
    <div class="inside">
        <?php
        $arrayOption = array(
            'menuIzquierda' => $this->menuIzquierda,
            'itemSelect' => $this->itemSelect,
            'actionName' => $this->actionName,
            'lang' => $this->lang,
            'controllerName' => $this->controllerName
        );
        echo $this->render('render/menuizq.phtml', $arrayOption); //vista rederizada para el menu izquierda 
        ?>
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <p><?php echo $this->modeRecomendate['tituloPaginaModRecomendarSite'] ?></p>
                <form action="" method="POST" class="frm_recomender dlgrid">
                    <fieldset class="dlinline">
                        <div class="w100">
                            <dl class="dt50 dd50">
                                <dt><label><?php echo $this->modeRecomendate['labelNombreModRecomendarSite'] ?></label></dt>
                                <dd><?php echo $this->form->yourname; ?></dd>
                            </dl>
                        </div>
                        <div class="w100">
                            <dl class="dt50 dd50">
                                <dt><label><?php echo $this->modeRecomendate['labelEmailModRecomendarSite'] ?></label></dt>
                                <dd><?php echo $this->form->youremail; ?></dd>
                            </dl>
                        </div>	
                        <div class="w100">
                            <dl class="dt50 dd50 box_sep">
                                <dt><label><?php echo $this->modeRecomendate['labelNombreDestinatarioModRecomendarSite'] ?></label></dt>
                                <dd><?php echo $this->form->recipientname; ?></dd>
                            </dl>
                        </div>	
                        <div class="w100 ">
                            <dl class="dt50 dd50 ">
                                <dt><label><?php echo $this->modeRecomendate['labelEmailDestinatarioModRecomendarSite'] ?></label></dt>
                                <dd><?php echo $this->form->recipientemail; ?></dd>
                            </dl>
                        </div>	
                        <div class="w100">
                            <dl class="dt50 dd50">
                                <dt>&nbsp;</dt>
                                <dd><?php echo $this->form->submit; ?></dd>
                            </dl>
                        </div>	
                    </fieldset>						
                </form>
            </div>	
        </section>
    </div>
</div>