
<div id="content" class="layout_fluid_inner">
    <div class="inside">
        <aside id="aside">
            <ul class="lst_aside">
                <li><a class="selected" href="#">Mentions légales </a></li>								
            </ul>
        </aside>
        <section id="" class="wrapp_content">
            <div class="wrapp_content_inner">
                <p>Indiquer votre email et celui de votre destinataire.</p>
                <form class="frm_recomender dlgrid">
                    <fieldset class="dlinline">
                        <div class="w100">
                            <dl class="dt50 dd50">
                                <dt><label>Votre nom et prénom</label></dt>
                                <dd><input type="text" class="text" /></dd>
                            </dl>
                        </div>
                        <div class="w100">
                            <dl class="dt50 dd50">
                                <dt><label>Votre email</label></dt>
                                <dd><input type="text" class="text" /></dd>
                            </dl>
                        </div>	
                        <div class="w100">
                            <dl class="dt50 dd50 box_sep">
                                <dt><label>Nom et Prénom du destinaire</label></dt>
                                <dd><input type="text" class="text" /></dd>
                            </dl>
                        </div>	
                        <div class="w100 ">
                            <dl class="dt50 dd50 ">
                                <dt><label>Email du destinataire</label></dt>
                                <dd><input type="text" class="text" /></dd>
                            </dl>
                        </div>	
                        <div class="w100">
                            <dl class="dt50 dd50">
                                <dt>&nbsp;</dt>
                                <dd><input type="submit" class="btn btn_submit whitegradient float_right" value="ENVOYER"/></dd>
                            </dl>
                        </div>	




                    </fieldset>						
                </form>
            </div>	
        </section>
    </div>
</div>