<div id="content" class="layout_fluid_inner">
    <div class="inside cf">

        <div class="box box_item_home">
            <h2>
                <span>Nouveautés</span>
            </h2>
            <div class="cf">	
                <div class="box_l">
                    <img src="/f/img/temp/img_item_home_1.jpg" />
                </div>
                <div class="box_r">
                    <h3>Coffret Saint Valentin</h3>
                    <p>Du portugais « barocco », le terme baroque désigne la forme irrégulière d’une perle.
                        Dès la fin de la Renaissance, il décrit un contraste artistique fort, mêlant l’ombre à la
                        lumière. En sculpture, peinture, littérature mais surtout en musique, l’art baroque est 
                        fait de paradoxes et d’exubérance.</p>
                </div>

            </div>
            <div class="box_b">
                <a href="#">+ En savoir plus</a>								
            </div>
        </div>

        <div class="box box_item_home last">
            <h2>
                <span>Actualités</span>
            </h2>
            <div class="cf">							
                <div class="box_l">
                    <img class="imgLeft" src="/actualites/<?php echo $this->listaActualites[0]['imagen']?>"/>
                </div>
                <div class="box_r">
                    <h3><?php echo $this->listaActualites[0]['titleActualitesIdioma']; ?></h3>
                        <?php echo $this->listaActualites[0]['contenidoActualitesIdioma']; ?>                    									
                </div>
            </div>	
            <div class="box_b">									
                <a href="/<?php echo $this->lang; ?>/arty-fragance/actualites">+ Lire la suite</a>	
            </div>
        </div>

    </div>

</div>