<div id="content" class="layout_fluid_inner">
    <div class="inside cf">

        <div class="box box_item_home">
            <h2>
                <span>Nouveautés</span>
            </h2>
            <div class="cf">	
                <div class="box_l">
                    <img class="imgRight" src="/realisations/<?php echo $this->listaNovedades[0]['imagen']?>"/>
                </div>
                <div class="box_r">
                    <h3><?php echo $this->listaNovedades[0]['titleRealisationsIdioma']; ?></h3>
                    <?php echo $this->listaNovedades[0]['contenidoRealisationsIdioma'] ?>
                </div>

            </div>
            <div class="box_b">
                <a href="#">+ En savoir plus</a>								
            </div>
        </div>

        <div class="box box_item_home last">
            <h2>
                <span>Actualités</span>
            </h2>
            <div class="cf">							
                <div class="box_l">
                    <img class="imgLeft" src="/actualites/<?php echo $this->listaActualites[0]['imagen']?>"/>
                </div>
                <div class="box_r">
                    <h3><?php echo $this->listaActualites[0]['titleActualitesIdioma']; ?></h3>
                        <?php echo $this->listaActualites[0]['contenidoActualitesIdioma']; ?>                    									
                </div>
            </div>	
            <div class="box_b">									
                <a href="/<?php echo $this->lang; ?>/arty-fragance/actualites">+ Lire la suite</a>	
            </div>
        </div>

    </div>

</div>