<!DOCTYPE html>
<!--[if lt IE 7]> <html lang="es-es" class="no-js ie6"> <![endif]-->
<!--[if IE 7]>    <html lang="es-es" class="no-js ie7"> <![endif]-->
<!--[if IE 8]>    <html lang="es-es" class="no-js ie8"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="es-es" class="no-js"> <!--<![endif]-->
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<title>index</title>
<link rel="stylesheet/less" type="text/css" href="css/screen.less?id=1">
<script src="js/less-1.1.5.min.js" type="text/javascript"></script>
<script src="js/jquery.js" type="text/javascript" charset="utf-8"></script>
<script src="js/jquery.cycle.all.js" type="text/javascript" charset="utf-8"></script>
<script src="js/main.js" type="text/javascript" charset="utf-8"></script>

<!--[if lt IE 9]>
  <script src="js/html5.js"></script>
<![endif]-->
<!--[if lt IE 10]>
    <link rel="stylesheet" href="css/ieonly.css" type="text/css" media="screen" />
<![endif]-->

</head>
<body id="" class="lyt_collection_intro" onLoad="">
	<div class="wrapper">
		<div class="wrapper_l">
		<div class="wrapper_r">
			<div class="wrapper_inner">
                            <div id="main_content" class="layout_fluid ">
					<div id="content" class="layout_fluid_inner">
						<div class="inside">
							<aside id="aside">
                                                            <?php 
                                                            $c = 0;
                                                            foreach ($this->articulo as $col): 
                                                                if($c==0){
                                                                    $first = $col;
                                                                    $c++;
                                                                    }?>                                                             
                                                            <ul class="lst_aside">
                                                                <li><a href="<?php echo "/collections/index/info1/".$col["idArticulo"] ?>"><h2><?php echo $col["titulo"]?></h2></a></li>
                                                                <li><a href="<?php echo "/collections/index/info1/".$col["idArticulo"] ?>">Presentacion</a></li>
                                                                        <?php foreach ($this->categoria as $prod): 
                                                                          if($col["idArticulo"] == $prod["idArticulo"]){
                                                                        ?>                                                                        
                                                                        <li><a class="" href="<?php echo "/collections/index/info2/".$prod["idCat"] ?>"><?php echo $prod["nombre"]?></a></li>
                                                                        <?php } ?>
                                                                        <?php endforeach; ?>
							    </ul>
                                                            <?php endforeach; ?>
								<!--<ul class="lst_aside selected">
									<li><h2>Collection de la Cour</h2></li>
									<li><a class="" href="#">Présentation</a></li>									
									<li><a class="selected" href="#">La Fleur du Roy</a></li>									
									<li><a class="" href="#">Le Rêve de la Reine</a></li>									
									<li><a class="" href="#">Délice des Libertins </a></li>									
									<li><a class="" href="#">Alcôve Royale </a></li>
								</ul>-->
							</aside>
                                                    <?php if($this->idCat) { ?>
                                                    <section id="" class="wrapp_content">
                                                            <div class="wrapp_content_inner">
                                                                <!--<h2>La Fleur du Roy
                                                                    <span><em>Bougies</em> - Savons - Huiles essentielles</span>
                                                                </h2>-->
                                                                <h2><?php echo $this->detaprod["nombre"]?>
                                                                    <span>
                                                                        <?php $con =0;
                                                                        foreach ($this->prod as $p):
                                                                            if($con ==0){
                                                                                $produ = $p;$con++;}
                                                                            ?>
                                                                        <a  class="" href="<?php echo "/collections/index/info3/".$p["idDetalleArticulo"] ?>"><?php echo $p["titulo"];?></a> | 
                                                                        <?php 
                                                                        endforeach;
                                                                        ?></span>
                                                                </h2>
                                                                <div class="slide_collection">
                                                                    <div class="mainphoto">
                                                                        <div class="photo">
                                                                            <?php foreach ($this->foto as $foto):
                                                                                
                                                                                $foto = "/imagen-producto/".$foto["nombreFoto"];
                                                                                ?>
                                                                            <div class="item">                                                                                
                                                                                <img class="" src="<?php echo $foto;?>" width="808" height="500"/>
                                                                                                                
                                                                                <div class="box_slide">
                                                                                    <a href="#" class="slideC slideUp"></a>
                                                                                    <div class="inner">
                                                                                    <?php echo $foto["descripcionFoto"] ?>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <?php endforeach;?>                                                                            
                                                                          							
                                                                        </div>                                                                        
                                                                        <div id="pager" class=""></div>
                                                                    </div>
                                                                    
                                                                                        
                                                                    <div class="description">
                                                                        <div class="description_l">                                                                            
                                                                            <?php echo $produ["parrafoDetalle"]?>                                                                            
                                                                        </div>
                                                                    </div>						
                                                                </div>	
                                                            </div>	
                                                        </section>          
                                                    
                                                    <?php } else if($this->idProd) { ?>
                                                    
                                                    <section id="" class="wrapp_content">
                                                            <div class="wrapp_content_inner">
                                                                <!--<h2>La Fleur du Roy
                                                                    <span><em>Bougies</em> - Savons - Huiles essentielles</span>
                                                                </h2>-->
                                                                <h2><?php echo $this->detaprod["nombre"]?>
                                                                    <span>
                                                                        <?php $con =0;
                                                                        foreach ($this->prod as $p):
                                                                            if($con ==0){
                                                                                $produ = $p;$con++;}
                                                                            ?>
                                                                        <a  class="" href="<?php echo "/collections/index/info3/".$p["idDetalleArticulo"] ?>"><?php echo $p["titulo"];?></a> | 
                                                                        <?php 
                                                                        endforeach;
                                                                        ?></span>
                                                                </h2>
                                                                <div class="slide_collection">
                                                                    <div class="mainphoto">
                                                                        <div class="photo">
                                                                            <?php foreach ($this->foto as $foto):
                                                                                if($foto["idDetalleArticulo"] == $produ["idDetalleArticulo"]):
                                                                                $foto = "/imagen-producto/".$foto["nombreFoto"];
                                                                                ?>
                                                                            <div class="item">                                                                                
                                                                                <img class="" src="<?php echo $foto;?>" width="808" height="500"/>
                                                                                                                
                                                                                <div class="box_slide">
                                                                                    <a href="#" class="slideC slideUp"></a>
                                                                                    <div class="inner">
                                                                                    <?php echo $foto["descripcionFoto"] ?>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <?php endif; endforeach;?>                                                                            
                                                                          							
                                                                        </div>                                                                        
                                                                        <div id="pager" class=""></div>
                                                                    </div>
                                                                    
                                                                                        
                                                                    <div class="description">
                                                                        <div class="description_l">                                                                            
                                                                            <?php echo $produ["parrafoDetalle"]?>                                                                            
                                                                        </div>
                                                                    </div>						
                                                                </div>	
                                                            </div>	
                                                        </section>                                                    
                                                    
                                                    <?php } else 
                                                        if($this->idArt){ 
                                                        ?>                                                    
                                                    <section id="" class="wrapp_content">
								<div class="wrapp_content_inner">
                                                                    <?php $foto = "/imagen-articulo/".$this->detart["fotoPrincipal"]?>
									<img class="float_left" src="<?php echo $foto ?>" width="808"/>
									
                                                                        <?php echo $this->detart["parrafo"] ?>
									
								</div>	
                                                    </section>
                                                    
                                                    <?php } else { ?>
                                                    <section id="" class="wrapp_content">
								<div class="wrapp_content_inner">
                                                                    <?php $foto = "/imagen-articulo/".$first["fotoPrincipal"]?>
									<img class="float_left" src="<?php echo $foto ?>" width="808"/>									
                                                                        <?php echo $first["parrafo"] ?>
									
								</div>	
                                                    </section>
                                                    <?php } ?>
						</div>
					</div>
				</div>
			</div>
		</div>
		</div>
	</div>
	<div class="wrapper_b">
	</div>
</body>
</html>