<td valign="top">
    <div id="centerPane">
        <div id="toolbar">
            <a class="modules" href="<?php $this->baseUrl() ?>/admin/index">Ini</a> &gt; <a class="actualités" href="<?php $this->baseUrl() ?>/admin/index/Realisations/"><?php echo $this->params['action'] ?></a> &gt; Modifier               
        </div>
        <div id="main">
            <!--   <h2 class="top"></h2>-->
            <div id="form">
                <?php
                echo $this->render(
                        'render/listaIdioma.phtml', array(
                    'idms' => $this->idms,
                    'lang' => $this->lang,
                ));
                ?>
           <!-- End Language -->
                <div class="table_admin">
                    <div class="table_admin_head"></div>
                    <div align="center" class="table_admin_body">
                        <input type="hidden" value="9" name="id">
                        <div><?php echo is_array($this->mensaje)?$this->mensaje[0]:''; ?></div>
                        <fieldset>
                            <legend 
                                style="cursor : pointer" 
                                onclick="openCloseLayer('listmodules')">
                                <img align="top" src="/images/icons/package.png"> Liste de Realisations</legend>
                            <div id="listmodules" style="display: block; padding: 2px 10px;">
                                <table width="100%" cellspacing="0" cellpadding="0" border="0">
                                    <thead>
                                        <tr>
                                            <th>Title</th>
                                            <th>Imagen</th>
                                            <th>Link</th>
                                            <th>Options</th>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    </thead>

                                    <tbody>

                                        <?php
                                        $countCoulm = 1;
                                        foreach ($this->listaRealisations as $value):
                                            $cssColum = (($countCoulm%2)==1)?'':'shadow';
                                            if ((int) $value['activoRealisations'] == 1):
                                                $iconStatus = "_status.png";
                                                $alert = CAlertMenuOFF;
                                                $title = CTitleMenuOFF;
                                            else:
                                                $iconStatus = '_status-red.png';
                                                $alert = CAlertMenuOFF;
                                                $title = CTitleMenuOFF;
                                            endif;
                                            $countCoulm++;
                                            ?>
                                            <tr class="<?php echo $cssColum; ?>">
                                                <td width="35%" >
                                                    <?php echo $value['titleRealisationsIdioma']; ?>
                                                </td>
                                                <td width="25%">
                                                    <img width="70" src="<?php echo $this->baseUrl() ?>/Realisations/thums_<?php echo $value['imagen']; ?>" >
                                                </td>
                                                <td width="25%">
                                                    <a href="<?php echo $value['link']; ?>">Link</a>
                                                </td>
                                                <td align="right" width="15%">
                                                    <a href="/admin/nouveautes/edit-nouveautes/id/<?php echo $value['idRealisations'] ?>" 
                                                       title="Modifier">
                                                        <img border="0" src="/images/icons/edit.gif">
                                                    </a>
                                                    <!--                                                <a class="status-config" href="/admin/module/config/id/Realisations/mode/desinstaller" title="Enlever le module">-->
                                                    <img border="0" 
                                                         title="<?php echo $title; ?>" 
                                                         src="/images/icons/<?php echo $iconStatus;?>" 
                                                         onclick="desactiveItem('<?php echo $value['idRealisations'] ?>','<?php echo $alert; ?>','/admin/realisations/desactivar-realisations/id',<?php echo $value['activoRealisations'] ?>)" 
                                                         style="cursor: pointer;" >
                                                    <img border="0" 
                                                         title="<?php echo CTitleDelete; ?>" 
                                                         src="/images/icons/delete.png" 
                                                         onclick="deleteItem('<?php echo $value['idRealisations'] ?>','<?php echo CAlertDelete; ?>','/admin/realisations/eliminar-realisations/id')" 
                                                         style="cursor: pointer;" >
                                                    <!--                                                </a>-->

                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td align="right" valign="bottom" colspan="5">
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <a href="/admin/nouveautes/new-nouveautes"> Nouveau</a>
                        </fieldset>

                    </div>
                    <div class="table_admin_foot"></div>
                </div>


                <!-- jQuery -->
            </div>
        </div>

        <!-- <div id="options" class="column" >
                             </div>-->

    </div>
</td>