<td valign="top">
    <div id="centerPane">
        <div id="toolbar">
           <a class="modules" href="<?php $this->baseUrl()?>/admin/pointventa/index">Liste Point Vente</a> &gt; <a class="actualités" href="<?php $this->baseUrl()?>/admin/index/actualites/"><?php echo $this->params['action']?></a> &gt; Modifier               
        <div id="main">
            <!--   <h2 class="top"></h2>-->
            <div id="form">
                    <?php 
                        echo $this->render('render/listaIdioma.phtml',
                            array(
                                'idms' => $this->idms,
                                'lang' => $this->lang,
                            )
                        );
                    ?>


                    <div class="table_admin">
                        <div class="table_admin_head"></div>
                        <div align="center" class="table_admin_body">
                            <input type="hidden" value="3" name="id">
                            <form id="frmDevenir" enctype="multipart/form-data" method="post" action="">
                            <table cellspacing="0" cellpadding="0" border="0" width="100%" class="table_form">
                                <tbody>
                                    <tr><th colspan="2">
                                        </th></tr>
                                    
                                    <tr><th colspan="2">
                                        </th>
                                    </tr>
                                    <tr>
                                        <td align="left" width="20%">Cod : *</td>
                                        <td align="left" width="80%"> 
                                            <input type="hidden" name="idPais" value="<?php echo $this->data['idPais']?>" />
                                            
                                            <input type="text" value="<?php echo $this->data['idPais']?>"  size="20" name="hidPais" disabled="disabled" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="left" width="20%">Nom : *</td>
                                        <td align="left" width="80%">
                                            <input type="text" value="<?php echo $this->data['nombrePaisIdioma']?>" class="required" size="40" maxlength="100" name="nombrePaisIdioma" id="nombrePaisIdioma" />
                                        </td>
                                    </tr>

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td align="right" valign="bottom" colspan="3">
                                            <input type="submit" value="Valider" name="">
                                            <input type="button" onclick="location.href='/admin/pointventa';" value="Back" name="cancel">    </td>
                                    </tr>
                                </tfoot>
                            </table>
                            </form>
                        </div>
                        <div class="table_admin_foot"></div>
                    </div>
                
            </div>
        </div>

        <!-- <div id="options" class="column" >
                             </div>-->

    </div>
</td>

<script>

function getComboIdioma(value){
    var urls = document.URL;
    var data = urls.split('/idlang/');
    location.href = data[0] + '/idlang/' +  value
}

    $(document).ready(function(){

        $("#frmDevenir").validate({
            rules: {
                nombrePaisIdioma: "required"

            },

            messages: {
                nombrePaisIdioma: "Ce champ c'est obligatoire"
            }
        });
        $("#frmDevenir").validate();
    });
</script>
