<script type="text/javascript">
window.onload = function()
{
CKEDITOR.replace('descripcionBlogFotos');
}
</script>
<td valign="top">
    <div id="centerPane">
        <div id="toolbar">
            <a class="modules" 
               href="<?php echo $this->baseUrl() ?>/admin/collection/index">Collections</a> &gt; <a class="actualités" href="<?php //$this->baseUrl() ?>/admin/index/actualites/"><?php echo $this->params['action'] ?>
            </a> 
               &gt; New
            <div id="main">
                <div id="form">
                        <?php 
                                echo $this->render(
                                'render/listaIdioma.phtml',
                                array(
                                    'idms' => $this->idms,
                                    'lang' => $this->lang,
                                    ));
                        ?>
                        <div class="table_admin">                            
                            <div class="table_admin_head"></div>
                            <div align="center" class="table_admin_body">
                                <form action="" method="POST">
                                <table cellspacing="0" cellpadding="0" border="0" width="100%" class="table_form">
                                    <tbody>
                                        <tr><th colspan="2">
                                            </th></tr>
                                        <tr>
                                            <td align="left" width="20%">lien *</td>
                                            <td align="left" width="80%">
                                                <?php echo $this->form->linkBlogFotos; ?>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td align="left" width="20%">lien montrer*</td>
                                            <td align="left" width="80%">
                                                <?php echo $this->form->nombreLinkBlogFotos; ?>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td align="left" width="20%">Image *</td>
                                            <td align="left" width="80%">
                                                <?php echo $this->form->fotoPrincipal; ?>
                                                <button id="upload_button">Upload</button>
                                                
                                            </td>
                                            
                                        </tr>
                                        
                                        <tr>
                                            <td colspan="4">
                                                <div id="lista">
                                                </div>
                                                
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td align="left" width="14%" valign="top">Description *</td>
                                            <td align="left" colspan="2">                                                
                                                <?php echo $this->form->descripcionBlogFotos; ?>
                                            </td>
                                        </tr>

                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td align="right" valign="bottom" colspan="3">
                                                <?php echo $this->form->submit?>
                                                <input type="button" onclick="location.href='/admin/index/collections/idMenu/3';" value="Annuler" name="cancel">    
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                                    </form>
                            </div>
                            <div class="table_admin_foot"></div>
                        </div>
                               
                </div>
            </div>
        </div>
</td>

<script languaje="javascript"> 
$(document).ready(function(){
	var button = $('#upload_button'), interval;
	new AjaxUpload('#upload_button', {
        action: '/admin/elisabeth-de-feydeau/subir-imagenes-biografia?moduleAdmin=blog',
		onSubmit : function(file , ext){
		if (! (ext && /^(jpg|png|jpeg|gif)$/.test(ext))){
			alert('Error: Solo se permiten imagenes');
			return false;
		} else {
			button.text('Uploading....');
			this.disable();
		}
		},
		onComplete: function(file, response){
			button.text('Upload');
			this.enable();
                        printFotos();               
		}	
	});
        $("[id^=elminarFoto]").live("click",function(){
        var idImgArray = this.id.split('-');
        $.ajax({
                data: "idImg="+idImgArray[1],
                type: "POST",
                dataType: "json",
                url: "/admin/elisabeth-de-feydeau/eliminar-foto-blog/",
                success: function(data){
                    printFotos()
                }
            });
        });

printFotos();           

});

function printFotos(){
        $.ajax({
                data: "as=asd",
                type: "GET",
                dataType: "json",
                url: "<?php $this->baseUrl() ?>/admin/elisabeth-de-feydeau/listar-imagenes-blog/",
                success: function(data){
                    $("#lista").html(data);
                    
                }
            });
            
        }
        
            
</script>
