<script type="text/javascript">
window.onload = function()
{
CKEDITOR.replace('parrafo');
}
</script>
<td valign="top">
    <div id="centerPane">
        <div id="toolbar">
            <a class="modules" href="<?php //$this->baseUrl() ?>/admin/collection/index">Collections</a> &gt; <a class="actualités" href="<?php //$this->baseUrl() ?>/admin/index/actualites/"><?php echo $this->params['action'] ?></a> &gt; New
            <div id="main">
                <div id="form">
                        <?php 
                            echo $this->render('render/listaIdioma.phtml',
                                array(
                                    'idms' => $this->idms,
                                    'lang' => $this->lang,
                                )
                            );
                        ?>
                        <div class="table_admin">                            
                            <div class="table_admin_head"></div>
                            <div align="center" class="table_admin_body">                                
                                <table cellspacing="0" cellpadding="0" border="0" width="100%" class="table_form">
                                    <tbody>
                                        <tr><th colspan="2">
                                            </th></tr>
                                        <tr>
                                            <td align="left" width="20%">Title *</td>
                                            <td align="left" width="80%">
                                                <?php echo $this->form->titulo; ?>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td align="left" width="20%">Imagen *</td>
                                            <td align="left" width="80%">
                                                <?php echo $this->form->fotoPrincipal; ?>
                                            </td>
                                        </tr>
                                        
                                        <tr>
                                            <td align="left" width="14%" valign="top">Description *</td>
                                            <td align="left" colspan="2">                                                
                                                <?php echo $this->form->parrafo; ?>
                                            </td>
                                        </tr>

                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td align="right" valign="bottom" colspan="3">
                                                <?php echo $this->form->submit?>
                                                <input type="button" onclick="location.href='/admin/index/collections/idMenu/3';" value="Annuler" name="cancel">    
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <div class="table_admin_foot"></div>
                        </div>
                               
                </div>
            </div>
        </div>
</td>
