<aside id="aside">
    <ul class="lst_aside">
        <?php 
        foreach($this->menuIzquierda as $index=>$valor): 
            $rutCont = $valor['idTipoMenu']==1?'/cont':'';
            ?>
        <li><?php if($valor['idTipoMenu']==2 && $this->itemSelect==''){?>
            <a class="<?php echo $this->actionName==$valor['rutaMenuBase']?'selected':'' ?>" 
            <?php } else { ?>   
            <a class="<?php echo $this->itemSelect==$index?'selected':'' ?>"    
            <?php }  ?>   
               href="/<?php echo $this->lang==''?'':$this->lang.'/' ?><?php echo $this->controllerName.$rutCont.'/'.$valor['rutaMenuBase'] ?>"><?php echo ucwords(strtolower($valor['nombreMenu']))?>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
</aside>