<aside id="aside">
    <ul class="lst_aside">
        <?php 
        foreach($this->menuIzquierda as $index=>$valor): ?>
        <li>
            <a class="<?php echo $this->itemSelect==$index?'selected':'' ?>" 
               href="/<?php echo $this->lang==''?'':$this->lang.'/' ?><?php echo $this->controllerName.'/'.$valor['rutaMenuBase'] ?>"><?php echo $valor['nombreMenu']?>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
</aside>