<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<!--[if lt IE 7]> <html lang="es-es" class="no-js ie6"> <![endif]-->
<!--[if IE 7]>    <html lang="es-es" class="no-js ie7"> <![endif]-->
<!--[if IE 8]>    <html lang="es-es" class="no-js ie8"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" xmlns:fb="http://ogp.me/ns/fb#"> 
    <!--<![endif]-->
<head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <?php echo $this->headStyle() ?>
<link rel="stylesheet/less" type="text/css" href="/f/css/screen.less?id=1">
<script src="/f/js/less-1.1.5.min.js" type="text/javascript"></script>
<script src="/f/js/jquery.js" type="text/javascript" charset="utf-8"></script>
        <?php echo $this->headLink() ?>
<!--[if lt IE 9]>
  <script src="/f/js/html5.js"></script>
<![endif]-->
<!--[if lt IE 10]>
    <link rel="stylesheet" href="/f/css/ieonly.css" type="text/css" media="screen" />
<![endif]-->
</head>
<body id="" class="lyt_intro" onLoad="">
	<div class="wrapper">
		<div class="wrap_intro">
		<?php echo $this->layout()->content ?>
                </div>
	</div>
	<script type="text/javascript">
		$(document).ready(function(){
			
		});
	</script>
</body>
</html>